### PR TITLE
refactor: Change scroll throtle and distance

### PR DESCRIPTION
**Pull request by giovanneguerra**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204058949837564

### CODE REVIEW

**Comment by smakhtin** [comment]
@giovanneguerra Something weird is happening with internal state. When i open lion profile, then go back to the table the table kind of losing its fetched state (strange for SPA) and then i always able to scroll to the lion with id `ff`, then the scroll stops working. Looks like something is happening when i go from page to page, so the state (fetched lions) is getting messed out.

**Comment by smakhtin** [comment]
@giovanneguerra Something weird is happening with internal state. When i open lion profile, then go back to the table the table kind of losing its fetched state (strange for SPA) and then i always able to scroll to the lion with id `ff`, then the scroll stops working. Looks like something is happening when i go from page to page, so the state (fetched lions) is getting messed out.

**Comment by smakhtin** [comment]
ListRecord

@giovanneguerra Something is still wrong with the state. When i go back and forth to the page i see that records are basically repeated in the main list. Please see the GIF for explanation.

**Comment by giovanneguerra** [comment]
> 

I just tested it now in the current preview and don't see the same behavior.

**Comment by smakhtin** [comment]
> > 
> 
> I just tested it now in the current preview and don't see the same behavior.

I can reproduce it: 
- Open a panel page.
- Click view on any lion after scroll event landed.
- Click back in browser.
- Scroll and you will see that data is cycled.

**Pull request closed without merging**
