### PR TITLE
Feature/create tests

### PR DESCRIPTION
**Pull request by giovanneguerra**
Create more tests

### CODE REVIEW

**Comment by smakhtin** [comment]
@giovanneguerra Tests are falling because there is no DB available. I think the easiest way is to mock database access. Check [requests mocking here](https://vitest.dev/guide/mocking.html).

**Comment by giovanneguerra** [comment]
> 

About this issue, I'm trying to see a way to configure the GraphQL server in the tests.
After experimenting a while, I see that if I configure _graphql-client.clients.default.host_ in _nuxt.config.ts_ with the correct address it will automatically mock the components for us.

I suggest we implement this with the build and dev environments.

**Comment by smakhtin** [comment]
@giovanneguerra Can you please send here the example for correct `nuxt.config.ts`?

**Comment by giovanneguerra** [comment]
> @giovanneguerra Can you please send here the example for correct `nuxt.config.ts`?

For me this should be the way that the runtimeConfig is set-up, also need to put the vars in the .env file.
Then this variables should be set in the CI with the build path for then in the case of the GQL_HOST. 
A suggestion that I see to keep the variables concise between the developers in the project is to push a _.env.example_ file with the vars blank so the developer can fill it properly.


runtimeConfig: {
    public: {
      'graphql-client': {
        clients: {
          default: {
            host: process.env.GQL_HOST,
            schema: './schema.gql'
          }
        }
      },
      mapboxToken: process.env.MAPBOX_TOKEN
    }
  }

**Pull request merged**
